apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 4
          periodSeconds: 4
      dnsPolicy: ClusterFirst

---

  apiVersion: v1
  kind: Service
  metadata:
    name: grafana
    labels:
      app: grafana
  spec:
    ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
    type: LoadBalancer
    loadBalancerIP: 172.17.0.244