apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never

---

  apiVersion: v1
  kind: Service
  metadata:
    name: phpmyadmin
    labels:
      app: phpmyadmin
  spec:
    ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 80
    selector:
      app: phpmyadmin
    type: LoadBalancer
    loadBalancerIP: 172.17.0.243